#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename

#SBATCH --time=48:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=16   # 16 processor core(s) per node
#SBATCH --partition=scavenger  # huge node(s)
#SBATCH --job-name="trimAl_run"
#SBATCH --mail-user=sharmig@iastate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output="trimAl.output" # job standard output file (%j replaced by job id)
#SBATCH --error="trimAl.error" # job standard error file (%j replaced by job id)

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE

#trimAl v1.5.rev0 build[2024-05-27]



# Run trimAl with the 'gappyout' strategy on the combined MAFFT alignment file
trimal -gappyout -in Combined_opsins.aa.mafft-einsi.fa -out Combined_opsins.aa.mafft-einsi.trimal-gappy.fa

